# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpcDefinitions.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rpcDefinitions.proto',
  package='inteledgecloud',
  syntax='proto3',
  serialized_pb=_b('\n\x14rpcDefinitions.proto\x12\x0einteledgecloud\"\x89\x01\n\x0fServiceResponse\x12\x13\n\x0bServiceName\x18\x01 \x01(\t\x12\x16\n\x0eProcessingTime\x18\x02 \x01(\x05\x12\x14\n\x0cResponseData\x18\x03 \x01(\t\x12\x33\n\x10RequestParameter\x18\x04 \x03(\x0b\x32\x19.inteledgecloud.Parameter\"\"\n\x10\x46ibanacciRequest\x12\x0e\n\x06number\x18\x01 \x01(\x05\"-\n\x0bHashRequest\x12\x0c\n\x04Type\x18\x01 \x01(\t\x12\x10\n\x08InputLen\x18\x02 \x01(\x05\"1\n\x0b\x45tcdRequest\x12\x10\n\x08putCount\x18\x01 \x01(\x05\x12\x10\n\x08getCount\x18\x02 \x01(\x05\"\'\n\tParameter\x12\x0b\n\x03Key\x18\x01 \x01(\t\x12\r\n\x05Value\x18\x02 \x01(\t\"\x07\n\x05\x45mpty2\xd0\x02\n\rSampleService\x12N\n\x0cGenerateHash\x12\x1b.inteledgecloud.HashRequest\x1a\x1f.inteledgecloud.ServiceResponse\"\x00\x12W\n\x10PerformFibinacci\x12 .inteledgecloud.FibanacciRequest\x1a\x1f.inteledgecloud.ServiceResponse\"\x00\x12G\n\x0bPerformNoOp\x12\x15.inteledgecloud.Empty\x1a\x1f.inteledgecloud.ServiceResponse\"\x00\x12M\n\x0bPerformEtcd\x12\x1b.inteledgecloud.EtcdRequest\x1a\x1f.inteledgecloud.ServiceResponse\"\x00\x62\x06proto3')
)




_SERVICERESPONSE = _descriptor.Descriptor(
  name='ServiceResponse',
  full_name='inteledgecloud.ServiceResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ServiceName', full_name='inteledgecloud.ServiceResponse.ServiceName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ProcessingTime', full_name='inteledgecloud.ServiceResponse.ProcessingTime', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ResponseData', full_name='inteledgecloud.ServiceResponse.ResponseData', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='RequestParameter', full_name='inteledgecloud.ServiceResponse.RequestParameter', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=178,
)


_FIBANACCIREQUEST = _descriptor.Descriptor(
  name='FibanacciRequest',
  full_name='inteledgecloud.FibanacciRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='inteledgecloud.FibanacciRequest.number', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=180,
  serialized_end=214,
)


_HASHREQUEST = _descriptor.Descriptor(
  name='HashRequest',
  full_name='inteledgecloud.HashRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Type', full_name='inteledgecloud.HashRequest.Type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='InputLen', full_name='inteledgecloud.HashRequest.InputLen', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=216,
  serialized_end=261,
)


_ETCDREQUEST = _descriptor.Descriptor(
  name='EtcdRequest',
  full_name='inteledgecloud.EtcdRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='putCount', full_name='inteledgecloud.EtcdRequest.putCount', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='getCount', full_name='inteledgecloud.EtcdRequest.getCount', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=263,
  serialized_end=312,
)


_PARAMETER = _descriptor.Descriptor(
  name='Parameter',
  full_name='inteledgecloud.Parameter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Key', full_name='inteledgecloud.Parameter.Key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Value', full_name='inteledgecloud.Parameter.Value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=314,
  serialized_end=353,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='inteledgecloud.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=355,
  serialized_end=362,
)

_SERVICERESPONSE.fields_by_name['RequestParameter'].message_type = _PARAMETER
DESCRIPTOR.message_types_by_name['ServiceResponse'] = _SERVICERESPONSE
DESCRIPTOR.message_types_by_name['FibanacciRequest'] = _FIBANACCIREQUEST
DESCRIPTOR.message_types_by_name['HashRequest'] = _HASHREQUEST
DESCRIPTOR.message_types_by_name['EtcdRequest'] = _ETCDREQUEST
DESCRIPTOR.message_types_by_name['Parameter'] = _PARAMETER
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ServiceResponse = _reflection.GeneratedProtocolMessageType('ServiceResponse', (_message.Message,), dict(
  DESCRIPTOR = _SERVICERESPONSE,
  __module__ = 'rpcDefinitions_pb2'
  # @@protoc_insertion_point(class_scope:inteledgecloud.ServiceResponse)
  ))
_sym_db.RegisterMessage(ServiceResponse)

FibanacciRequest = _reflection.GeneratedProtocolMessageType('FibanacciRequest', (_message.Message,), dict(
  DESCRIPTOR = _FIBANACCIREQUEST,
  __module__ = 'rpcDefinitions_pb2'
  # @@protoc_insertion_point(class_scope:inteledgecloud.FibanacciRequest)
  ))
_sym_db.RegisterMessage(FibanacciRequest)

HashRequest = _reflection.GeneratedProtocolMessageType('HashRequest', (_message.Message,), dict(
  DESCRIPTOR = _HASHREQUEST,
  __module__ = 'rpcDefinitions_pb2'
  # @@protoc_insertion_point(class_scope:inteledgecloud.HashRequest)
  ))
_sym_db.RegisterMessage(HashRequest)

EtcdRequest = _reflection.GeneratedProtocolMessageType('EtcdRequest', (_message.Message,), dict(
  DESCRIPTOR = _ETCDREQUEST,
  __module__ = 'rpcDefinitions_pb2'
  # @@protoc_insertion_point(class_scope:inteledgecloud.EtcdRequest)
  ))
_sym_db.RegisterMessage(EtcdRequest)

Parameter = _reflection.GeneratedProtocolMessageType('Parameter', (_message.Message,), dict(
  DESCRIPTOR = _PARAMETER,
  __module__ = 'rpcDefinitions_pb2'
  # @@protoc_insertion_point(class_scope:inteledgecloud.Parameter)
  ))
_sym_db.RegisterMessage(Parameter)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'rpcDefinitions_pb2'
  # @@protoc_insertion_point(class_scope:inteledgecloud.Empty)
  ))
_sym_db.RegisterMessage(Empty)



_SAMPLESERVICE = _descriptor.ServiceDescriptor(
  name='SampleService',
  full_name='inteledgecloud.SampleService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=365,
  serialized_end=701,
  methods=[
  _descriptor.MethodDescriptor(
    name='GenerateHash',
    full_name='inteledgecloud.SampleService.GenerateHash',
    index=0,
    containing_service=None,
    input_type=_HASHREQUEST,
    output_type=_SERVICERESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='PerformFibinacci',
    full_name='inteledgecloud.SampleService.PerformFibinacci',
    index=1,
    containing_service=None,
    input_type=_FIBANACCIREQUEST,
    output_type=_SERVICERESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='PerformNoOp',
    full_name='inteledgecloud.SampleService.PerformNoOp',
    index=2,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_SERVICERESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='PerformEtcd',
    full_name='inteledgecloud.SampleService.PerformEtcd',
    index=3,
    containing_service=None,
    input_type=_ETCDREQUEST,
    output_type=_SERVICERESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SAMPLESERVICE)

DESCRIPTOR.services_by_name['SampleService'] = _SAMPLESERVICE

# @@protoc_insertion_point(module_scope)
