apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-performance-mapper-app-deployment
spec:
  selector:
    matchLabels:
      app: workload-mapper-app
      #  replicas: 3 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: workload-mapper-app
    spec:
      containers:
      - name: workload-mapper-app
        image: patrickkutch/workloadmapper
#        imagePullPolicy: Always
        args: ["-r", "app", "-c", "localhost:80"]          
        
        env:
        - name: PYTHONUNBUFFERED
          value: "0"        
        ports:
        - name: app-port 
          containerPort: 80
        
      - name: workload-mapper-service
        image: patrickkutch/workloadmapper
#        imagePullPolicy: Always
        args: ["-r", "app", "-c", "localhost:80"]          
        
        env:
        - name: PYTHONUNBUFFERED
          value: "0"        
        ports:
        - name: app-port 
          containerPort: 80
