kind: Service
apiVersion: v1
metadata:
  name: wpm-hash-appremote-service
  namespace: app-at-edge-ns
  labels:
    locale: appremote
    
spec:
  selector:
    wpm-pod: wpm-app-hash
    locale: appremote
  ports:
  - protocol: TCP
    port: 80 
---

kind: Service
apiVersion: v1
metadata:
  name: wpm-fibinacci-appremote-service
  namespace: app-at-edge-ns
  labels:
    locale: appremote
  
spec:
  selector:
    wpm-pod: wpm-app-fibinacci
    locale: appremote
  ports:
  - protocol: TCP
    port: 80 
 
---
kind: Service
apiVersion: v1
metadata:
  name: wpm-noop-appremote-service
  namespace: app-at-edge-ns
  labels:
    locale: appremote
  
spec:
  selector:
    wpm-pod: wpm-app-noop
    locale: appremote
  ports:
  - protocol: TCP
    port: 80 
---          
apiVersion: v1
kind: Pod
metadata:
  name: wpm-fibinacci-appremote-pod
  namespace: app-at-edge-ns 
  labels:
    wpm-pod: wpm-app-fibinacci
    locale: appremote
    
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: placement 
            operator: NotIn
            values:
            - app-node
    
  containers:
  - name: workload-mapper-service-fibinacci
    image: patrickkutch/workloadmapper
    args: ["-r", "service", "-c", "localhost:80"]          
    
    env:
    - name: PYTHONUNBUFFERED
      value: "0"        
    ports:
    - name: app-port 
      containerPort: 80
---          

apiVersion: v1
kind: Pod
metadata:
  name: wpm-hash-appremote-pod
  namespace: app-at-edge-ns   
  labels:
    wpm-pod: wpm-app-hash
    locale: appremote

spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: placement 
            operator: NotIn
            values:
            - app-node

  containers:
  - name: workload-mapper-service-hash
    image: patrickkutch/workloadmapper
    args: ["-r", "service", "-c", "localhost:80"]          
    
    env:
    - name: PYTHONUNBUFFERED
      value: "0"        
    ports:
    - name: app-port 
      containerPort: 80
---

apiVersion: v1
kind: Pod
metadata:
  name: wpm-noop-appremote-pod
  namespace: app-at-edge-ns   
  labels:
    wpm-pod: wpm-app-noop
    locale: appremote
    
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: placement 
            operator: NotIn
            values:
            - app-node

  containers:
  - name: workload-mapper-service-noop
    image: patrickkutch/workloadmapper
    args: ["-r", "service", "-c", "localhost:80"]          
    
    env:
    - name: PYTHONUNBUFFERED
      value: "0"        
    ports:
    - name: app-port 
      containerPort: 80