kind: Service
apiVersion: v1
metadata:
  name: wpm-hash-applocal-service
spec:
  selector:
    wpm-service: wpm-workload-mapper-app
  ports:
  - protocol: TCP
    port: 80 
---

kind: Service
apiVersion: v1
metadata:
  name: wpm-fibinacci-applocal-service
spec:
  selector:
    app: workload-mapper-app
  ports:
  - protocol: TCP
    port: 80 
 
---
kind: Service
apiVersion: v1
metadata:
  name: wpm-noop-applocal-service
spec:
  selector:
    app: workload-mapper-app
  ports:
  - protocol: TCP
    port: 80 
---          
apiVersion: v1
kind: Pod
metadata:
  name: wpm-fibinacci-applocal-pod
  labels:
    app: workload-mapper-service-fibinacci
    locale: applocal
    
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: placement 
            operator: In
            values:
            - app-node
    
  containers:
  - name: workload-mapper-service-fibinacci
    image: patrickkutch/workloadmapper
    args: ["-r", "service", "-c", "localhost:80"]          
    
    env:
    - name: PYTHONUNBUFFERED
      value: "0"        
    ports:
    - name: app-port 
      containerPort: 80
---          

apiVersion: v1
kind: Pod
metadata:
  name: wpm-hash-applocal-pod
  labels:
    app: workload-mapper-service-hash
    locale: applocal
    
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: placement 
            operator: In
            values:
            - app-node

  containers:
  - name: workload-mapper-service-hash
    image: patrickkutch/workloadmapper
    args: ["-r", "service", "-c", "localhost:80"]          
    
    env:
    - name: PYTHONUNBUFFERED
      value: "0"        
    ports:
    - name: app-port 
      containerPort: 80
---

apiVersion: v1
kind: Pod
metadata:
  name: wpm-noop-applocal-pod
  labels:
    app: workload-mapper-service-noop
    locale: applocal
    
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: placement 
            operator: In
            values:
            - app-node

  containers:
  - name: workload-mapper-service-noop
    image: patrickkutch/workloadmapper
    args: ["-r", "service", "-c", "localhost:80"]          
    
    env:
    - name: PYTHONUNBUFFERED
      value: "0"        
    ports:
    - name: app-port 
      containerPort: 80