kind: Service
apiVersion: v1
metadata:
  name: wpm-web-app-svc
  namespace: app-at-edge-ns

spec:
  type: NodePort
  selector:
    app: wpm-web-app-pod
  ports:
  - protocol: TCP
    port: 80 
    nodePort: 32001 
---

apiVersion: v1
kind: Pod
metadata:
  name: wpm-web-app-pod
  namespace: app-at-edge-ns   

spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: placement 
            operator: In
            values:
            - app-node

  containers:
  - name: workload-mapper-service-hash
    image: patrickkutch/workloadmapper
    args: ["-r", "app", "-c", "localhost:80"]          
    
    env:
    - name: PYTHONUNBUFFERED
      value: "0"        
    ports:
    - name: app-port 
      containerPort: 80

    envFrom:
    - configMapRef:
        name: wpm-web-app-configmap





