kind: Service
apiVersion: v1
metadata:
  name: workload-perf-mapper-app-svc
  namespace: app-at-edge-ns

spec:
  type: NodePort
  selector:
    app: workload-mapper-app
  ports:
  - protocol: TCP
    port: 80 
    nodePort: 32001 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-performance-mapper-app-deployment
  namespace: app-at-edge-ns
  
spec:
  selector:
    matchLabels:
      app: workload-mapper-app
  template:
    metadata:
      labels:
        app: workload-mapper-app
    spec:
      nodeSelector:
        placement: app-node
      containers:
      - name: workload-mapper-app
        image: patrickkutch/workloadmapper
        args: ["-r", "app", "-c", "localhost:80"]          
        
        env:  # for logging
        - name: PYTHONUNBUFFERED
          value: "0"        
        ports:
        - name: app-port 
          containerPort: 80
        
