kind: Service
apiVersion: v1
metadata:
  name: wpm-webapp-svc
  namespace: app-at-edge-ns
  wpm-label: wpm-app

spec:
  type: NodePort
  selector:
    wpm-pod: wpm-webapp-pod
  ports:
  - protocol: TCP
    port: 80 
    nodePort: 32001 
---

apiVersion: v1
kind: Pod
metadata:
  name: wpm-webapp-pod
  namespace: app-at-edge-ns   
  labels:
    wpm-pod: wpm-webapp-pod

spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: placement 
            operator: In
            values:
            - app-node

  containers:
  - name: wpm-webapp-pod
    image: patrickkutch/workloadmapper
    imagePullPolicy: Always    
    args: ["-v", "3","-r", "app", "-c", "0.0.0.0:80"]          
    
    env:
    - name: PYTHONUNBUFFERED
      value: "0"        
    ports:
    - name: app-port 
      containerPort: 80
      
    volumeMounts:
    - name: service-discovery-volume
      mountPath: /var/workloadmapper
      
  volumes:
    - name: service-discovery-volume
      configMap:
        name: wpm-webapp-configmap
        





